# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.5
  - nightly
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Documenter")'
  - julia -e 'ENV["DOCUMENTER_DEBUG"] = "true"; using Pkg;import Helium; cd(joinpath(dirname(pathof(Helium)), "..", "docs")); include("make.jl")'
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
    - stage: "Documentation"
      julia: 1.5
      os: linux
      script: julia --color=yes --project=docs -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
      after_success: skip
